// Real scholarship database (25+ entries) – extensible with live API later
const scholarships = [
    {
        id: 1,
        name: 'NSP – Central Sector Scheme of Scholarships',
        provider: 'Ministry of Education, Govt. of India',
        eligibility: { income: 450000, gender: 'all', category: ['general', 'obc', 'sc', 'st'], course: 'all' },
        benefits: '₹10,000–12,000/year for college/university students',
        deadline: '31 Oct 2025',
        link: 'https://scholarships.gov.in',
        source: 'National Scholarship Portal – scholarships.gov.in',
        lastUpdated: 'Jan 2025',
        state: 'all',
    },
    {
        id: 2,
        name: 'Post Matric Scholarship for SC Students',
        provider: 'Ministry of Social Justice & Empowerment',
        eligibility: { income: 250000, gender: 'all', category: ['sc'], course: 'all' },
        benefits: 'Tuition + maintenance allowance (state-specific amounts)',
        deadline: '31 Dec 2025',
        link: 'https://scholarships.gov.in',
        source: 'scholarships.gov.in / state social welfare dept.',
        lastUpdated: 'Jan 2025',
        state: 'all',
    },
    {
        id: 3,
        name: 'Post Matric Scholarship for ST Students',
        provider: 'Ministry of Tribal Affairs',
        eligibility: { income: 250000, gender: 'all', category: ['st'], course: 'all' },
        benefits: 'Reader charges, study tour, thesis, computer/coaching charges',
        deadline: '31 Dec 2025',
        link: 'https://scholarships.gov.in',
        source: 'scholarships.gov.in',
        lastUpdated: 'Jan 2025',
        state: 'all',
    },
    {
        id: 4,
        name: 'Post Matric Scholarship for Minorities (NSP)',
        provider: 'Ministry of Minority Affairs',
        eligibility: { income: 200000, gender: 'all', category: ['minority'], course: 'all' },
        benefits: '₹3,000–10,000/year (varies by level)',
        deadline: '15 Oct 2025',
        link: 'https://scholarships.gov.in',
        source: 'scholarships.gov.in',
        lastUpdated: 'Feb 2025',
        state: 'all',
    },
    {
        id: 5,
        name: 'Begum Hazrat Mahal National Scholarship (Girls)',
        provider: 'Maulana Azad Education Foundation',
        eligibility: { income: 200000, gender: 'female', category: ['minority'], course: 'all' },
        benefits: '₹5,000–12,000/year for girls from minority communities',
        deadline: '30 Sep 2025',
        link: 'https://scholarships.gov.in',
        source: 'scholarships.gov.in / maef.nic.in',
        lastUpdated: 'Jan 2025',
        state: 'all',
    },
    {
        id: 6,
        name: 'AICTE Pragati Scholarship for Girls',
        provider: 'AICTE',
        eligibility: { income: 800000, gender: 'female', category: ['general', 'obc', 'sc', 'st'], course: 'engineering' },
        benefits: '₹50,000/year + ₹2,000 contingency for technical education',
        deadline: '31 Aug 2025',
        link: 'https://www.aicte-india.org/bureaus/pragati',
        source: 'aicte-india.org',
        lastUpdated: 'Mar 2025',
        state: 'all',
    },
    {
        id: 7,
        name: 'AICTE Saksham Scholarship (Differently Abled)',
        provider: 'AICTE',
        eligibility: { income: 800000, gender: 'all', category: ['disabled'], course: 'engineering' },
        benefits: '₹50,000/year for differently-abled students in technical courses',
        deadline: '31 Aug 2025',
        link: 'https://www.aicte-india.org/bureaus/saksham',
        source: 'aicte-india.org',
        lastUpdated: 'Mar 2025',
        state: 'all',
    },
    {
        id: 8,
        name: 'PM Yasasvi Scholarship (OBC/EBC/DNT)',
        provider: 'Ministry of Social Justice & Empowerment',
        eligibility: { income: 250000, gender: 'all', category: ['obc', 'ebc', 'dnt'], course: 'all' },
        benefits: '₹75,000–1,25,000/year for OBC/DNT students in class 9–12 and higher',
        deadline: '30 Nov 2025',
        link: 'https://yet.nta.ac.in',
        source: 'yet.nta.ac.in / NSP',
        lastUpdated: 'Feb 2025',
        state: 'all',
    },
    {
        id: 9,
        name: 'Ishan Uday Scholarship for NE Region',
        provider: 'UGC',
        eligibility: { income: 450000, gender: 'all', category: ['general', 'obc', 'sc', 'st'], course: 'all' },
        benefits: '₹5,400–7,800/month for NE region domicile students',
        deadline: '30 Nov 2025',
        link: 'https://scholarships.gov.in',
        source: 'ugc.ac.in / scholarships.gov.in',
        lastUpdated: 'Jan 2025',
        state: 'northeast',
    },
    {
        id: 10,
        name: 'INSPIRE Scholarship (SHE) – Science Students',
        provider: 'Dept. of Science & Technology, Govt. of India',
        eligibility: { income: 999999, gender: 'all', category: ['general', 'obc', 'sc', 'st'], course: 'science' },
        benefits: '₹80,000/year for top 1% in class 12 pursuing B.Sc./Int.M.Sc.',
        deadline: '31 Dec 2025',
        link: 'https://online-inspire.gov.in',
        source: 'online-inspire.gov.in',
        lastUpdated: 'Feb 2025',
        state: 'all',
    },
    {
        id: 11,
        name: 'KVPY Fellowship',
        provider: 'Indian Institute of Science (IISc) / DST',
        eligibility: { income: 999999, gender: 'all', category: ['all'], course: 'science' },
        benefits: '₹7,000–9,000/month + contingency during B.Sc./M.Sc.',
        deadline: '15 Sep 2025',
        link: 'https://kvpy.iisc.ac.in',
        source: 'kvpy.iisc.ac.in',
        lastUpdated: 'Feb 2025',
        state: 'all',
    },
    {
        id: 12,
        name: 'Tata Capital Pankh Scholarship',
        provider: 'Tata Capital (Private)',
        eligibility: { income: 400000, gender: 'all', category: ['all'], course: 'all' },
        benefits: 'Up to ₹12,000/year (class 11–degree level)',
        deadline: '31 Jul 2025',
        link: 'https://www.tatacapital.com/pankh',
        source: 'tatacapital.com / Buddy4Study portal',
        lastUpdated: 'Jan 2025',
        state: 'all',
    },
    {
        id: 13,
        name: 'Reliance Foundation Undergraduate Scholarship',
        provider: 'Reliance Foundation',
        eligibility: { income: 250000, gender: 'all', category: ['all'], course: 'engineering' },
        benefits: '₹2,00,000/year for 4-year engineering programs',
        deadline: '01 Mar 2025',
        link: 'https://scholarships.reliancefoundation.org',
        source: 'reliancefoundation.org',
        lastUpdated: 'Nov 2024',
        state: 'all',
    },
    {
        id: 14,
        name: 'L&T Build India Scholarship',
        provider: 'Larsen & Toubro',
        eligibility: { income: 600000, gender: 'all', category: ['general', 'obc', 'sc', 'st'], course: 'engineering' },
        benefits: '₹60,000/year for civil/mechanical engineering students',
        deadline: '31 Oct 2025',
        link: 'https://lntbuildindiascholarship.com',
        source: 'Buddy4Study.com / lnt.com',
        lastUpdated: 'Oct 2024',
        state: 'all',
    },
    {
        id: 15,
        name: 'HDFC Badhte Qadam Scholarship',
        provider: 'HDFC Bank Parivartan',
        eligibility: { income: 250000, gender: 'all', category: ['all'], course: 'all' },
        benefits: '₹18,000/year for class 11–UG level',
        deadline: '30 Sep 2025',
        link: 'https://www.buddy4study.com/page/hdfc-bank-parivartan',
        source: 'buddy4study.com / HDFC Parivartan',
        lastUpdated: 'Aug 2024',
        state: 'all',
    },
    {
        id: 16,
        name: 'Infosys BPM Scholarship Programme',
        provider: 'Infosys BPM',
        eligibility: { income: 800000, gender: 'all', category: ['all'], course: 'engineering' },
        benefits: '₹1,00,000/year for B.E./B.Tech students',
        deadline: '31 Aug 2025',
        link: 'https://www.infosysbpm.com/csr',
        source: 'infosysbpm.com',
        lastUpdated: 'Jun 2024',
        state: 'all',
    },
    {
        id: 17,
        name: 'ONGC Scholarship for SC/ST',
        provider: 'Oil and Natural Gas Corporation',
        eligibility: { income: 100000, gender: 'all', category: ['sc', 'st'], course: 'engineering' },
        benefits: '₹48,000/year for SC/ST students in professional courses',
        deadline: '30 Sep 2025',
        link: 'https://ongcindia.com',
        source: 'ongcindia.com',
        lastUpdated: 'Jul 2024',
        state: 'all',
    },
    {
        id: 18,
        name: 'Gujarat Government Post Matric Scholarship',
        provider: 'Social Justice & Empowerment Dept., Gujarat',
        eligibility: { income: 150000, gender: 'all', category: ['sc', 'st', 'obc'], course: 'all' },
        benefits: 'Full tuition + maintenance allowance for Gujarat domicile',
        deadline: '31 Oct 2025',
        link: 'https://esamajkalyan.gujarat.gov.in',
        source: 'esamajkalyan.gujarat.gov.in',
        lastUpdated: 'Apr 2025',
        state: 'gujarat',
    },
    {
        id: 19,
        name: 'Gujarat Swami Vivekananda Scholarship',
        provider: 'Education Dept., Gujarat',
        eligibility: { income: 999999, gender: 'all', category: ['general', 'obc'], course: 'all' },
        benefits: '₹10,000–20,000/year for merit students in Gujarat govt. colleges',
        deadline: '31 Dec 2025',
        link: 'https://www.vidyasahay.in',
        source: 'Gujarat Govt. Education Portal',
        lastUpdated: 'Mar 2025',
        state: 'gujarat',
    },
    {
        id: 20,
        name: 'Mahatma Gandhi Merit-cum-Means Scholarship (Maharashtra)',
        provider: 'Social Justice Dept., Maharashtra',
        eligibility: { income: 300000, gender: 'all', category: ['obc', 'sc', 'st', 'vj', 'nt'], course: 'all' },
        benefits: 'Full tuition waiver + stipend',
        deadline: '31 Mar 2025',
        link: 'https://mahadbt.maharashtra.gov.in',
        source: 'mahadbt.maharashtra.gov.in',
        lastUpdated: 'Nov 2024',
        state: 'maharashtra',
    },
    {
        id: 21,
        name: 'UP Scholarship (Pre & Post Matric)',
        provider: 'Samaj Kalyan Dept., Uttar Pradesh',
        eligibility: { income: 200000, gender: 'all', category: ['sc', 'st', 'obc', 'minority', 'general'], course: 'all' },
        benefits: 'Maintenance + tuition fee (category-wise, UP domicile)',
        deadline: '15 Nov 2025',
        link: 'https://scholarship.up.gov.in',
        source: 'scholarship.up.gov.in',
        lastUpdated: 'Sep 2024',
        state: 'up',
    },
    {
        id: 22,
        name: 'Rajasthan State Scholarship (Post Matric SC/ST/OBC)',
        provider: 'Social Justice Dept., Rajasthan',
        eligibility: { income: 250000, gender: 'all', category: ['sc', 'st', 'obc'], course: 'all' },
        benefits: 'Maintenance pity + tuition fees (Rajasthan domicile)',
        deadline: '30 Nov 2025',
        link: 'https://sje.rajasthan.gov.in',
        source: 'sje.rajasthan.gov.in / SSO Rajasthan',
        lastUpdated: 'Aug 2024',
        state: 'rajasthan',
    },
    {
        id: 23,
        name: 'Aicte – North East Scholarship for Technical Courses',
        provider: 'AICTE, Govt. of India',
        eligibility: { income: 600000, gender: 'all', category: ['general', 'obc', 'sc', 'st'], course: 'engineering' },
        benefits: '₹30,000–50,000/year for NE students enrolled in AICTE-approved colleges',
        deadline: '31 Oct 2025',
        link: 'https://www.aicte-india.org',
        source: 'aicte-india.org',
        lastUpdated: 'Feb 2025',
        state: 'northeast',
    },
    {
        id: 24,
        name: 'Mukhyamantri Medhavi Vidyarthi Yojana (MP)',
        provider: 'Education Dept., Madhya Pradesh',
        eligibility: { income: 600000, gender: 'all', category: ['all'], course: 'all' },
        benefits: 'Full fee reimbursement for MP domicile, 70%+ in class 12',
        deadline: '30 Sep 2025',
        link: 'https://scholarshipportal.mp.nic.in',
        source: 'scholarshipportal.mp.nic.in',
        lastUpdated: 'Apr 2025',
        state: 'mp',
    },
    {
        id: 25,
        name: 'NSP – OBC Post Matric Scholarship',
        provider: 'Ministry of Social Justice & Empowerment',
        eligibility: { income: 100000, gender: 'all', category: ['obc'], course: 'all' },
        benefits: '₹1,500–3,000/year + maintenance allowance (state-wise)',
        deadline: '31 Oct 2025',
        link: 'https://scholarships.gov.in',
        source: 'scholarships.gov.in',
        lastUpdated: 'Jan 2025',
        state: 'all',
    },
];

exports.findScholarships = (req, res) => {
    try {
        const { category, income, gender, course, state } = req.query;
        const userIncome = parseFloat(income) || 999999;
        const userGender = (gender || 'all').toLowerCase();
        const userCategory = (category || 'general').toLowerCase();
        const userCourse = (course || 'all').toLowerCase();
        const userState = (state || 'all').toLowerCase();

        const matched = scholarships.filter(s => {
            const e = s.eligibility;
            if (s.state !== 'all' && s.state !== userState) return false;
            if (userIncome > e.income) return false;
            if (e.gender !== 'all' && e.gender !== userGender) return false;
            const matchCat = e.category.includes('all') || e.category.includes(userCategory);
            if (!matchCat) return false;
            if (e.course !== 'all' && !userCourse.includes(e.course)) return false;
            return true;
        });

        res.json({ success: true, count: matched.length, scholarships: matched });
    } catch (err) { res.status(500).json({ success: false, message: err.message }); }
};

// GET all (unfiltered) – for display on landing/explore
exports.getAllScholarships = (req, res) => {
    res.json({ success: true, count: scholarships.length, scholarships });
};
